version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ms-mobile-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
  redis:
    image: redis:latest
    container_name: ms-mobile-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:10.3
    container_name: notifications-postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-manager
      - PGDATA=/tmp
